DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO(ID INT AUTO_INCREMENT PRIMARY KEY, NUMEROMATRICULA VARCHAR(50), NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);


-- para test --
INSERT INTO ODONTOLOGO(NUMEROMATRICULA, NOMBRE, APELLIDO) VALUES ('1234', 'Gerardo', 'Arias');